runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /less
  static_dir: less
